version: '3'
services:
######################## admin
  bot:
    image: bot:latest
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/wait-for-it.sh -q -s -h postgres -p 5432 -- /app/entrypoint.sh
    restart: always
    volumes:
      - /opt/help_data/static:/app/static
      - /opt/help_data/media:/app/media
    networks:
      - layer
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
######################## nginx
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public.pem:/etc/nginx/public.pem:ro
      - ./private.key:/etc/nginx/private.key:ro
      - /opt/help_data/static:/app/static:ro
      - /opt/help_data/media:/app/media:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - bot
    networks:
      - layer
######################## postgres
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - /opt/help_data/postgres:/var/lib/postgresql/data
    logging:
      driver: syslog
      options:
        tag: postgres
        syslog-facility: local6
    networks:
      - layer
######################## redis
  redis:
    image: redis:latest
    entrypoint: redis-server --appendonly yes --maxmemory-policy volatile-ttl --aof-use-rdb-preamble yes --save "" --maxclients 65000
    volumes:
      - /opt/help_data/redis:/data
    logging:
      driver: syslog
      options:
        tag: redis
        syslog-facility: local6
    networks:
      - layer
######################## queue sender
  sender:
    image: bot:latest
    entrypoint: celery -A app worker -c 2 -l INFO -Q sender
    deploy:
      mode: replicated
      replicas: 5
    restart: always
    depends_on:
      - redis
      - postgres
    volumes:
      - /opt/help_data/media:/app/media
    env_file:
      - .env
    networks:
      - layer
######################## flower
  flower:
    image: bot:latest
    entrypoint: celery -A app flower -l INFO --host=0.0.0.0 --port=5555
    restart: always
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - layer
networks:
  layer:
    driver: bridge
