# Generated by Django 4.2.7 on 2023-11-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_schedule_address_remove_speciality_rating_1_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['speciality'], name='bot_doctor_special_71e3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='polyclinic',
            index=models.Index(fields=['district'], name='bot_polycli_distric_549b25_idx'),
        ),
        migrations.AddIndex(
            model_name='speciality',
            index=models.Index(fields=['name'], name='bot_special_name_720536_idx'),
        ),
    ]
