# Generated by Django 4.2.7 on 2023-11-19 10:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_doctor_bot_doctor_special_71e3d6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('description', models.TextField(verbose_name='Description')),
                ('sum', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Sum')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
            },
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='rating',
            new_name='rating_general',
        ),
        migrations.RemoveField(
            model_name='polyclinic',
            name='rating',
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='rating_general',
            field=models.CharField(blank=True, choices=[('1', 'First place'), ('2', 'Second place'), ('3', 'Third place'), ('4', 'Fourth place'), ('5', 'Fifth place')], null=True, verbose_name='General rating'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='rating_share',
            field=models.CharField(blank=True, choices=[('1', 'First place'), ('2', 'Second place'), ('3', 'Third place'), ('4', 'Fourth place'), ('5', 'Fifth place')], null=True, verbose_name='Share rating'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='share',
            field=models.ManyToManyField(blank=True, to='bot.share', verbose_name='Share'),
        ),
    ]
