# Generated by Django 4.2.7 on 2023-11-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_squashed_0004_alter_doctor_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='polyclinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.polyclinic', verbose_name='Polyclinic'),
            preserve_default=False,
        ),
    ]
