# Generated by Django 4.2.7 on 2023-11-20 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_share_rename_rating_doctor_rating_general_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='rating_general',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='polyclinic',
            name='rating_general',
        ),
        migrations.RemoveField(
            model_name='polyclinic',
            name='rating_share',
        ),
        migrations.RemoveField(
            model_name='polyclinic',
            name='share',
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', 'First place'), ('2', 'Second place'), ('3', 'Third place'), ('4', 'Fourth place'), ('5', 'Fifth place')], null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='share',
            name='image',
            field=models.ImageField(blank=True, default='images/None.png', upload_to='images/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='share',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', 'First place'), ('2', 'Second place'), ('3', 'Third place'), ('4', 'Fourth place'), ('5', 'Fifth place')], null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='share',
            name='sum',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Sum'),
        ),
    ]
