# Generated by Django 4.2.7 on 2023-11-03 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_schedule_polyclinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cost',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='district',
            field=models.ManyToManyField(related_name='district', to='bot.district'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First_name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='polyclinic',
            field=models.ManyToManyField(related_name='polyclinic', to='bot.polyclinic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.position'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.ManyToManyField(related_name='schedule', to='bot.schedule'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.speciality'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='polyclinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.polyclinic'),
        ),
    ]
