# Generated by Django 4.2.7 on 2023-11-04 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_doctor_cost_alter_doctor_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last name')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Is bot')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='district',
            field=models.ManyToManyField(related_name='district', to='bot.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='polyclinic',
            field=models.ManyToManyField(related_name='polyclinic', to='bot.polyclinic', verbose_name='Polyclinic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.ManyToManyField(related_name='schedule', to='bot.schedule', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.speciality', verbose_name='Speciality'),
        ),
    ]
