# Generated by Django 4.2.7 on 2023-11-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='rating_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_1', to='bot.doctor', verbose_name='Rating 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='rating_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_2', to='bot.doctor', verbose_name='Rating 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='rating_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_3', to='bot.doctor', verbose_name='Rating 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='rating_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_4', to='bot.doctor', verbose_name='Rating 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='rating_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_5', to='bot.doctor', verbose_name='Rating 5'),
            preserve_default=False,
        ),
    ]
