# Generated by Django 4.2.7 on 2023-11-08 23:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_speciality_rating_1_alter_speciality_rating_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyclinic',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_set', to='bot.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='image',
            field=models.ImageField(blank=True, default='images/NoneClinic.jpg', upload_to='images/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, related_name='position_set', to='bot.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='site_url',
            field=models.URLField(blank=True, null=True, verbose_name='Site URL'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='speciality',
            field=models.ManyToManyField(related_name='speciality_set', to='bot.speciality', verbose_name='Speciality'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='work_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Work time end'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='work_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Work time start'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='bot.speciality', verbose_name='Speciality'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='Number')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polyclinic_set', to='bot.polyclinic', verbose_name='Polyclinic')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='phone',
            field=models.ManyToManyField(related_name='phone', to='bot.phone', verbose_name='Phones'),
        ),
    ]
