# Generated by Django 4.2.7 on 2023-11-11 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_polyclinic_district_polyclinic_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Phone number', 'verbose_name_plural': 'Phone numbers'},
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='name',
            new_name='polyclinic',
        ),
        migrations.RemoveField(
            model_name='polyclinic',
            name='address',
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='position',
            field=models.ManyToManyField(related_name='position_set', to='bot.position', verbose_name='Position'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100, verbose_name='Address')),
                ('polyclinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polyclinic_address', to='bot.polyclinic', verbose_name='Polyclinic')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='address',
            field=models.ManyToManyField(related_name='address_set', to='bot.address', verbose_name='Addresses'),
        ),
    ]
