# Generated by Django 4.2.7 on 2023-11-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_phone_options_rename_name_phone_polyclinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_schedule', to='bot.address', verbose_name='Address'),
        ),
    ]
