# Generated by Django 4.2.7 on 2023-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_alter_phone_number_alter_schedule_polyclinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyclinic',
            name='address',
        ),
        migrations.RemoveField(
            model_name='polyclinic',
            name='phone',
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='polyclinic',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='Phone'),
        ),
    ]
